# Generated by Django 4.2 on 2024-05-30 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Статья')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/image', verbose_name='изображение')),
                ('number_views', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('date_publications', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('publication_sign', models.BooleanField(default=False, verbose_name='признак публикации')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['title', 'date_publications'],
            },
        ),
    ]
