# Generated by Django 4.2 on 2024-05-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('Firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('Patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Клиент сервис',
                'verbose_name_plural': 'Клиенты сервиса',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('text', models.TextField(verbose_name='Текст письма')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.DateTimeField(verbose_name='дата и время первой отправки рассылки')),
                ('dispatch_time', models.DateTimeField(blank=True, null=True, verbose_name='время отправки')),
                ('date_time_end', models.DateTimeField(verbose_name='дата и время последней отправки рассылки')),
                ('period', models.CharField(choices=[('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], default='раз в день', max_length=50)),
                ('status', models.CharField(choices=[('завершено', 'завершено'), ('запущено', 'запущено'), ('создано', 'создано')], default='создано', max_length=50)),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'newsletter',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try_datatime', models.DateTimeField(auto_now=True, verbose_name='дата и время последней попытки')),
                ('status', models.CharField(blank=True, choices=[('success', 'успешно'), ('fail', 'неуспешно')], max_length=30, null=True, verbose_name='статус попытки')),
                ('mail_server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'db_table': 'reply',
            },
        ),
    ]
